version: "3.8"
services:
  mysqldb:
    container_name: mysqldb
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: employeedb
    networks:
      springboot-mysql-net:
  springrestws:
    container_name: springrestws
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - 