server:
  port: 9092
  servlet:
    context-path: /authserver
spring:
  application:
    name: authserver
management:
  endpoints:
    web:
      exposure:
        include: "*"
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
