server:
  port: 8090
  servlet:
    context-path: /productapp
spring:
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      path: /h2
      enabled: true
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb
    password: foo
    username: foo

logging:
  level:
    org:
      hibernate: ERROR
      springframework:
        web: DEBUG