version: "3.8"
services:
  springboot-app:
    container_name: spring-app
    image: springbooot-app
   # restart: always
    build: .
    depends_on:
      mysqldb:
        condition: service_healthy
    ports:
      - 8004:8080
    environment:
      MYSQL_HOST: mysqldb
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_PORT: 3306
    networks:
      - boot-mysql
  mysqldb:
    container_name: mysqldb
    image: mysql
    volumes:
      - c:/mysqldata/db:/var/lib/mysql
    ports:
      - 3307:3306
    environment:
      MYSQL_DATABASE: demo123
      MYSQL_ROOT_PASSWORD: root
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
      timeout: 20s
      retries: 10
    networks:
      - boot-mysql
networks:
  boot-mysql: